# From: https://github.com/marketplace/actions/compile-arduino-sketches
# Uses: https://github.com/arduino/compile-sketches
name: Arduino Compile Sketches

on: 
  push:
  workflow_dispatch:
    inputs:
      message:
        description: Message to display in job summary
        required: false
        type: string

jobs:
  compile-sketches: 
    name: call-compile-sketches-workflow
    uses: Andy4495/.github/.github/workflows/arduino-compile-sketches.yml@main
    with:
      message: ${{ inputs.message }}
      copyfile: ThingSpeakKeys
      fqbn: 'energia:tivac:EK-TM4C1294XL'
      platform-name: 'energia:tivac'
      platform-sourceurl: 'https://raw.githubusercontent.com/Andy4495/TI_Platform_Cores_For_Arduino/main/json/package_energia_minimal_TM4C_104_index.json'
      platform-version: latest
      libraries: |
        - source-path: ./
        - name: ArduinoJson
        - source-url: https://github.com/Andy4495/FutabaVFD162S.git
        - source-url: https://github.com/Andy4495/SparkFun_Micro_OLED_Arduino_Library.git
        - source-url: https://github.com/PaulStoffregen/Time.git
          version: v1.5



